// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB02MHqi0Q35KnlgL2USS1vw_iho7649Kw',
    appId: '1:189187943711:web:d711b05cefae662d6d942a',
    messagingSenderId: '189187943711',
    projectId: 'myapp4004',
    authDomain: 'myapp4004.firebaseapp.com',
    storageBucket: 'myapp4004.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OZ64uLu8jidrOBRdriBlejLMjrqcoCM',
    appId: '1:189187943711:android:be9cfcc58fc2d0796d942a',
    messagingSenderId: '189187943711',
    projectId: 'myapp4004',
    storageBucket: 'myapp4004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcouJLofQFeNDaukj0FHucWz8WPv4q698',
    appId: '1:189187943711:ios:4cb2c3552dec8d186d942a',
    messagingSenderId: '189187943711',
    projectId: 'myapp4004',
    storageBucket: 'myapp4004.appspot.com',
    iosBundleId: 'com.seance.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcouJLofQFeNDaukj0FHucWz8WPv4q698',
    appId: '1:189187943711:ios:4cb2c3552dec8d186d942a',
    messagingSenderId: '189187943711',
    projectId: 'myapp4004',
    storageBucket: 'myapp4004.appspot.com',
    iosBundleId: 'com.seance.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB02MHqi0Q35KnlgL2USS1vw_iho7649Kw',
    appId: '1:189187943711:web:0d6cfe374cc564166d942a',
    messagingSenderId: '189187943711',
    projectId: 'myapp4004',
    authDomain: 'myapp4004.firebaseapp.com',
    storageBucket: 'myapp4004.appspot.com',
  );
}
